---
title: "Construct Age-Length Keys"
author: "Derek H. Ogle, Northland College"
date: "16-Aug-2015"
output: pdf_document
geometry: margin=0.5in
---

```{r echo=FALSE, results='hide'}
library(knitr)
source("knitr_setup.R")
```

#Preliminaries
```{r results='hide', warning=FALSE, message=FALSE}
library(FSA)                                # for headtail(), alkPlot()
library(FSAdata)                            # for SpotVA2 data
library(dplyr)                              # for filter(), mutate()
library(nnet)                               # for multinom()
```

# Loading and Preparing Data
```{r}
data(SpotVA2)
headtail(SpotVA2)
```

```{r echo=FALSE, results='hide'}
# ############################################################
# This code demonstrates the use of is.na().  It is not needed
# for the analysis.
tmp <- headtail(SpotVA2) 
cbind(tmp,is.na(tmp$age),!is.na(tmp$age))
# ############################################################
```

```{r}
sp.len <- filter(SpotVA2,is.na(age))
headtail(sp.len)
sp.age <- filter(SpotVA2,!is.na(age))
headtail(sp.age)
```

```{r}
sp.age.mod <- mutate(sp.age,lcat=lencat(tl,w=1))
headtail(sp.age.mod)
```

# Observed Age-Length Key
```{r}
( raw <- xtabs(~lcat+age,data=sp.age.mod) )
( ALK.obs <- prop.table(raw,margin=1) )
```

# Smoothed Age-Length Key
```{r}
mlr <- multinom(age~lcat,data=sp.age.mod,maxit=500)
```
```{r}
lens <- 6:13
ALK.sm <- predict(mlr,data.frame(lcat=lens),type="probs")
row.names(ALK.sm) <- lens
round(ALK.sm,3)
```

# Visualizing an Age-Length Key
```{r fig.show='hold'}
alkPlot(ALK.obs,xlab="Total Length (cm)")
alkPlot(ALK.sm,xlab="Total Length (cm)")
```
```{r fig.show='hold'}
alkPlot(ALK.sm,xlab="Total Length (cm)",pal="gray",showLegend=TRUE)
alkPlot(ALK.sm,xlab="Total Length (cm)",pal="gray",showLegend=TRUE,type="area")
```
```{r fig.show='hold'}
alkPlot(ALK.sm,xlab="Total Length (cm)",pal="gray",type="lines")
alkPlot(ALK.sm,xlab="Total Length (cm)",type="bubble")
```

```{r echo=FALSE, results="hide", message=FALSE}
purl2("02_ALKConstruction.Rmd",moreItems="knitr",out.dir="scripts",topnotes="AFS Portland 16-Aug-15")
```
