---
title: "Apply An Age-Length Key"
author: "Derek H. Ogle, Northland College"
date: "16-Aug-2015"
output: pdf_document
geometry: margin=0.5in
---

```{r echo=FALSE, results='hide'}
library(knitr)
source("knitr_setup.R")
```

# Preliminaries
```{r results='hide', warning=FALSE, message=FALSE}
library(FSA)                             # for ... alkIndivAge(), Summarize(), fact2num()
library(dplyr)
library(nnet)
```

# Sourcing the Previous Script
```{r, results='hide', fig.show='hide'}
source("scripts/02_ALKConstruction.R")   # appropriately set the working directory before this
```
\vspace{-24pt}
```{r}
ls()
headtail(sp.len)
```

# Apply ALK using Isermann-Knight Method
```{r}
sp.len.mod <- alkIndivAge(ALK.obs,age~tl,data=sp.len)
headtail(sp.len.mod)
```

# Summarize Final Results
```{r}
sp.comb <- rbind(sp.age,sp.len.mod)
str(sp.comb)
```
```{r}
agefreq <- xtabs(~age,data=sp.comb)
prop.table(agefreq)
hist(~age,data=sp.comb,breaks=0:5,xlab="Age (yrs)")
```
```{r fig.show='hold'}
( sp.sum <- Summarize(tl~age,data=sp.comb,digits=2) )
plot(tl~age,data=sp.comb,ylab="Total Length (mm)",xlab="Age (yrs)",pch=16,col=rgb(0,0,0,0.1))
lines(mean~fact2num(age),data=sp.sum,col="blue",lwd=2)
```

```{r echo=FALSE, results="hide", message=FALSE}
purl2("03_ALKApplication.Rmd",moreItems="knitr",out.dir="scripts",topnotes="AFS Portland 16-Aug-15")
```
