---
title: "Fitting a von Bertalanffy Growth Function"
author: "Derek H. Ogle, Northland College"
date: "16-Aug-2015"
output: pdf_document
geometry: margin=0.5in
---

```{r echo=FALSE, results='hide'}
library(knitr)
source("knitr_setup.R")
```

# Preliminaries
```{r results='hide', warning=FALSE, message=FALSE}
library(FSA)                     # for headtail(), filterD(), vbModels(), vbStart(), vbFuns()
library(nlstools)                # for nlsBoot()
```

# Loading the Data and Some Preparations
```{r}
d <- read.csv("data/TroutBR.csv",header=TRUE)
rbt <- filterD(d,species=="Rainbow")
str(rbt)
```

```{r}
xlbl <- "Age (yrs)"
ylbl <- "Total Length (in)"
clr <- rgb(0,0,0,0.05)
```

# What Parameterizations are Available in FSA?
```{r fig.width=8, fig.height=4, out.width='.9\\linewidth', par1=TRUE}
vbModels()
```

# Fit Typical VBGF
## Declare a Function
```{r fig.width=8, fig.height=4, out.width='.98\\linewidth', par1=TRUE}
vb <- vbFuns("typical")
vb
```

## Find Starting Values
```{r fig.show='hold'}
svb.bad <- vbStarts(tl~age,data=rbt,type="typical",plot=TRUE)             # Left
svb <- vbStarts(tl~age,data=rbt,type="typical",meth0="yngAge",plot=TRUE)  # Right
unlist(svb)   # unlist() only to save space
```
```{r eval=FALSE}
# Dynamically approximately fit the function -- Can't be shown in a handout
vbStarts(tl~age,data=rbt,type="typical",dynamicPlot=TRUE)
svb2 <- list(Linf=28.7,K=0.52,t0=1.62)
```

\newpage

## Fit the Model
```{r}
fit1 <- nls(tl~vb(age,Linf,K,t0),data=rbt,start=svb)
summary(fit1)
( cf <- coef(fit1) )
confint(fit1)
```
```{r}
boot1 <- nlsBoot(fit1,niter=200)   # niter should be nearer 1000
confint(boot1)
```

## Make Predictions
```{r}
ageX <- 8
predict(fit1,data.frame(age=ageX))
```
```{r}
headtail(boot1$coefboot)
pv <- apply(boot1$coefboot,MARGIN=1,FUN=vb,t=ageX)
quantile(pv,c(0.025,0.975))
```

## Visualize the Fit
```{r par1=TRUE, fig.show='hold'}
plot(tl~age,data=rbt,xlab=xlbl,ylab=ylbl,pch=16,col=clr)
curve(vb(x,cf),from=3,to=10,n=500,lwd=2,col="red",add=TRUE)
```

```{r echo=FALSE, results="hide", message=FALSE}
purl2("04_GrowthFitting.Rmd",moreItems="knitr",out.dir="scripts",topnotes="AFS Portland 16-Aug-15")
```
